GET https://b2b-order-invoice.onrender.com/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo

### Register
POST https://b2b-order-invoice.onrender.com//api/auth/register
Content-Type: application/json

{
    "email": "shivam2@gmail.com",
    "password": "123456"
}

### Login
POST https://b2b-order-invoice.onrender.com//api/auth/login
Content-Type: application/json

{
    "email": "shivam2@gmail.com",
    "password": "123456"
}

### GET Items
GET https://b2b-order-invoice.onrender.com//api/orders/get-items

### Make Order
POST https://b2b-order-invoice.onrender.com//api/orders/make-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUzMjIxOTksImV4cCI6MTY3NjE4NjE5OSwiYXVkIjoiNjNkYjYxYjhmZjBmNWU1MGQxMmI0NzZkIn0.xqy6lphBYsz4k12pyoFhWzBK-1AaYT2wm8RAe_SnApY

{
    "itemCount": [
        {
            "itemId": "63d969ba20ee19f476c6aa24",
            "quantity": "6"
        },
        {
            "itemId": "63d9695920ee19f476c6aa20",
            "quantity": "3"
        }
    ] 
}

### User Orders
GET https://b2b-order-invoice.onrender.com//api/orders/user-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo


### GET Reciept
GET https://b2b-order-invoice.onrender.com//api/orders/invoice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo

{
    "orderId": "63da2d1fa0e7736226a1c547"
}

### Items
POST https://b2b-order-invoice.onrender.com//api/orders/add-item
Content-Type: application/json

{
    "DSIN": "MAG-100141.00",
    "NAME": "Magmus 3' S.S. Butt Door Hinges - Welded Soft Movement Matt 3' x 16",
    "MRP": "51",
    "HSN_CODE": "83021010",
    "GST": "18.0"
}

