GET http://localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo

### Login
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "email": "shivam1@gmail.com",
    "password": "123456"
}

### Register
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "email": "shivam1@gmail.com",
    "password": "123456"
}

### Make Order
POST http://localhost:8000/api/orders/make-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo

{
    "itemCount": [
        {
            "itemId": "63d9692420ee19f476c6aa1e",
            "quantity": "4"
        },
        {
            "itemId": "63d9695920ee19f476c6aa20",
            "quantity": "1"
        }
    ] 
}

### User Orders
GET http://localhost:8000/api/orders/user-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo


### GET Reciept
GET http://localhost:8000/api/orders/invoice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzUxODI5ODMsImV4cCI6MTY3NjA0Njk4MywiYXVkIjoiNjNkOTQxYjg4N2Q4ZTJiMmNlZjkzMWIwIn0.IPBrAc4-wgZ-WcTbED21N8f_W4_-STPoTZx7wU4qSKo

{
    "orderId": "63da2d1fa0e7736226a1c547"
}

# ### Items
# POST http://localhost:8000/api/orders/add-item
# Content-Type: application/json

# {
#     "DSIN": "MAG-100141.00",
#     "NAME": "Magmus 3' S.S. Butt Door Hinges - Welded Soft Movement Matt 3' x 16",
#     "MRP": "51",
#     "HSN_CODE": "83021010",
#     "GST": "18.0"
# }

